services:
  database:
    image: "postgis/postgis:16-3.4-alpine"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - path: ./.env
        required: false
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_DB: ${POSTGRES_DB:-codemeet_db}
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    env_file:
      - path: ./.env
        required: false
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://database:5432/codemeet_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "7777:8080"

  hive-router:
    image: "ghcr.io/graphql-hive/router:latest"
    ports:
      - "4000:4000"
    volumes:
    - ./graphql/router.config.yaml:/app/router.config.yaml
    - ./graphql/supergraph.graphql:/app/supergraph.graphql
    restart: unless-stopped
    depends_on:
      - app
    environment:
      LABORATORY_ENABLED: ${LABORATORY_ENABLED:-false}
volumes:
  db_data:
