supergraph:
  source: file
  path: /app/supergraph.graphql

override_subgraph_urls:
  REST_API:
    url: "http://app:8080"

laboratory:
  enabled: ${LABORATORY_ENABLED}

# TODO configure existing websocket connection
# https://the-guild.dev/graphql/hive/docs/router/subscriptions/websockets
