spring.application.name=backend
spring.config.import=optional:file:../.env[.properties]

# Database Connection
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/codemeet_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:12345}

# Hibernate Configuration (Auto-creates your tables based on your Java code)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.separator=^
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
# Syntax: ${ENV_VARIABLE:fallback_value}
jwt.secret=${JWT_SECRET:8a3c8e4b17a12b45e9d98f731a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b}
jwt.expiration=${JWT_EXPIRATION:86400000}
# 24 hours in milliseconds = 24 * 60 * 60 * 1000 = 86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload-dir=${user.home}/.codemeet/uploads/

